baseURL = "/"
languageCode = "en-us"
title = "Thick Dick Nick"
theme = "hugo-arcana"
copyright = "Copyright Â© 2023 Thick Dick Nick and Associates, LLC. All rights reserved"

[taxonomies]
    tag = "tags"

[params]
    description = "params description"
    show_post_dates = false

    [[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        url = "#"
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "#"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "#"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "#"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"


    [params.footer]

        [[params.footer.links]]
            header = "params footer links header"
        [[params.footer.links.links]]
            title = "Mattis et quis rutrum"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse amet varius"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"

        [[params.footer.links]]
            header = "params footer links header 2"
        [[params.footer.links.links]]
            title = "Duis neque nisi dapibus"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan sed"
            url = "#"

        [params.footer.contact_form]
            enabled = false
            header = "Get In Touch"
            action = ""
